### ISSUE TITLE
Shift lines in description

### ISSUE THREAD

**Issue by wandli** [ifedyukin/Mekyll#16]
Hi, 
I really like this theme and I tried to build my own page based on it.
However, I don't find my path to create a three-line description.
I want the page shows like this:

> A
B
C

But following the default setting of _config.yml, which contact lines automatically:
`description: >`
it will show like this:
> A B C

I have tried to 
1. use '|' instead of '>'
2. delete '>'
3. add '\n' after each line of my input in description

but nothing works.
I'm new to all of these. Could you please tell me what should I do?
Many thanks!

**Comment by ifedyukin** [comment]
As I've seen, you've already found a solution. Good luck :)
